accent = "#205EA6"
cursor = "#100F0F"
foreground = "#100F0F"
background = "#F4F5F7"
selection_foreground = "#100F0F"
selection_background = "#C9CED5"

color0 = "#100F0F"
color1 = "#AF3029"
color2 = "#66800B"
color3 = "#AD8301"
color4 = "#205EA6"
color5 = "#A02F6F"
color6 = "#24837B"
color7 = "#6B6E73"
color8 = "#B0B5BD"
color9 = "#D14D41"
color10 = "#879A39"
color11 = "#D0A215"
color12 = "#4385BE"
color13 = "#CE5D97"
color14 = "#3AA99F"
color15 = "#1C1B1A"
